// Builds icons.css: only the icons this site uses, as SVG masks, from the
// Font Awesome Free and Devicon packages. Replaces ~530 KiB of CDN icon fonts
// (and two render-blocking stylesheets) with one small same-origin file.
//
// Markup is unchanged: <i class="fas fa-x">, <i class="devicon-x-plain colored">.
// Each icon is drawn in currentColor, so colour, size and transform rules work
// exactly as they did with the fonts. Run after using a new icon:
//   node scripts/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const read = p => readFileSync(resolve(root, p), 'utf8');
const pkg = p => require.resolve(p, { paths: [root] });

const sources = ['index.html', 'script.js'].map(read).join('\n');
const UTILITY = new Set(['fa-spin', 'fa-fw']);
const faNames = [...new Set(sources.match(/\bfa-[a-z0-9-]+/g))].filter(n => !UTILITY.has(n)).sort();
const regular = new Set((sources.match(/\bfar fa-[a-z0-9-]+/g) || []).map(s => s.slice(4)));
const devNames = [...new Set(sources.match(/\bdevicon-[a-z0-9]+-(?:plain|original|line)(?:-wordmark)?\b/g))].sort();

// Minimal escaping keeps the data URIs readable and small.
const uri = svg => '"data:image/svg+xml,' + svg.replace(/"/g, "'").replace(/%/g, '%25').replace(/#/g, '%23')
  .replace(/</g, '%3C').replace(/>/g, '%3E').replace(/\s+/g, ' ') + '"';

/* — Font Awesome — */
const families = JSON.parse(readFileSync(pkg('@fortawesome/fontawesome-free/metadata/icon-families.json'), 'utf8'));
const byAlias = {};
for (const [name, d] of Object.entries(families)) ((d.aliases && d.aliases.names) || []).forEach(a => { byAlias[a] = name; });
const faSvg = (style, s) => {
  const path = Array.isArray(s.path) ? s.path.join(' ') : s.path;
  return { w: +(s.width / s.height).toFixed(4), svg: `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${s.width} ${s.height}'><path d='${path}'/></svg>` };
};
const rules = [];
const missing = [];
for (const cls of faNames) {
  const short = cls.slice(3);
  const d = families[short] || families[byAlias[short]];
  const svgs = d && d.svgs && d.svgs.classic;
  const style = svgs && (svgs.solid ? 'solid' : svgs.brands ? 'brands' : null);
  if (!style) { missing.push(cls); continue; }
  const { w, svg } = faSvg(style, svgs[style]);
  rules.push(`.${cls}{--ico:url(${uri(svg)});--w:${w}}`);
  if (regular.has(cls) && svgs.regular) {
    const r = faSvg('regular', svgs.regular);
    rules.push(`.far.${cls}{--ico:url(${uri(r.svg)});--w:${r.w}}`);
  }
}

/* — Devicon — */
const devCss = readFileSync(pkg('devicon/devicon.min.css'), 'utf8');
const colour = {};
for (const m of devCss.matchAll(/((?:\.devicon-[a-z0-9-]+\.colored,?)+)\{color:(#[0-9a-fA-F]+)\}/g)) {
  m[1].split(',').forEach(sel => { colour[sel.slice(1, -'.colored'.length)] = m[2]; });
}
// Some font glyphs have no SVG of their own: devicon.json aliases them to
// another version (nextjs "plain" is drawn from "original").
const devJson = JSON.parse(readFileSync(pkg('devicon/devicon.json'), 'utf8'));
for (const cls of devNames) {
  const [, icon, version] = cls.match(/^devicon-([a-z0-9]+)-(.+)$/);
  const entry = devJson.find(i => i.name === icon);
  const alias = entry && (entry.aliases || []).find(a => a.alias === version);
  const candidates = [version].concat(alias ? [alias.base] : []);
  let svg;
  for (const v of candidates) {
    try { svg = readFileSync(resolve(dirname(pkg('devicon/devicon.json')), 'icons', icon, `${icon}-${v}.svg`), 'utf8'); break; }
    catch {}
  }
  if (!svg) { missing.push(cls); continue; }
  svg = svg.replace(/<\?xml[^>]*>|<!--[\s\S]*?-->|<!DOCTYPE[^>]*>/g, '').trim()
    // One decimal on a 128-unit canvas is ~0.006px at icon size; it halves the biggest icons.
    .replace(/(\d+\.\d)\d+/g, '$1');
  rules.push(`.${cls}{--ico:url(${uri(svg)})}`);
  if (colour[cls]) rules.push(`.${cls}.colored{color:${colour[cls]}}`);
}

if (missing.length) { console.error('✗ no icon found for: ' + missing.join(', ')); process.exit(1); }

const css = `/* Generated by scripts/build-icons.mjs. Do not edit by hand.
   Font Awesome Free 6.5.0 icons: CC BY 4.0, https://fontawesome.com/license/free
   Devicon 2.15.1: MIT, https://devicon.dev */
.fas,.far,.fab,[class^="devicon-"],[class*=" devicon-"]{display:inline-block;flex:none;width:calc(var(--w,1)*1em);height:1em;vertical-align:-.125em;background-color:currentColor;-webkit-mask:var(--ico) center/contain no-repeat;mask:var(--ico) center/contain no-repeat}
.fa-spin{animation:fa-spin 1s linear infinite}
@keyframes fa-spin{to{transform:rotate(360deg)}}
@media (prefers-reduced-motion: reduce){.fa-spin{animation-duration:2s}}
${rules.join('\n')}
`;
writeFileSync(resolve(root, 'icons.css'), css);
console.log(`✓ icons.css: ${faNames.length} Font Awesome + ${devNames.length} Devicon icons, ${(css.length / 1024).toFixed(1)} KiB`);
